// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpellBookApi.Contexts;

#nullable disable

namespace SpellBookApi.Migrations
{
    [DbContext(typeof(SpellBookContext))]
    [Migration("20240918181320_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ReagentSpell", b =>
                {
                    b.Property<Guid>("ReagentsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ReagentsId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("ReagentSpell");

                    b.HasData(
                        new
                        {
                            ReagentsId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("c19099ed-94db-44ba-885b-0ad7205d5e40"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("0c4dc798-b38b-4a1c-905c-a9e76dbef17b"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("937b1ba1-7969-4324-9ab5-afb0e4d875e6"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("7a2fbc72-bb33-49de-bd23-c78fceb367fc"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("b5f336e2-c226-4389-aac3-2499325a3de9"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            SpellsId = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06")
                        },
                        new
                        {
                            ReagentsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            SpellsId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa")
                        },
                        new
                        {
                            ReagentsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            SpellsId = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa")
                        },
                        new
                        {
                            ReagentsId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            SpellsId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d")
                        },
                        new
                        {
                            ReagentsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            SpellsId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d")
                        },
                        new
                        {
                            ReagentsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            SpellsId = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d")
                        },
                        new
                        {
                            ReagentsId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            SpellsId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16")
                        },
                        new
                        {
                            ReagentsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            SpellsId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16")
                        },
                        new
                        {
                            ReagentsId = new Guid("e0017fe1-773f-4a59-9730-9489833c6e8e"),
                            SpellsId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16")
                        },
                        new
                        {
                            ReagentsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            SpellsId = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16")
                        },
                        new
                        {
                            ReagentsId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            SpellsId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a")
                        },
                        new
                        {
                            ReagentsId = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            SpellsId = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a")
                        });
                });

            modelBuilder.Entity("SpellBookApi.Entities.Reagent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reagents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Black Pearl"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "Blood Moss"
                        },
                        new
                        {
                            Id = new Guid("c19099ed-94db-44ba-885b-0ad7205d5e40"),
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("0c4dc798-b38b-4a1c-905c-a9e76dbef17b"),
                            Name = "Nightshade"
                        },
                        new
                        {
                            Id = new Guid("937b1ba1-7969-4324-9ab5-afb0e4d875e6"),
                            Name = "Ginseng"
                        },
                        new
                        {
                            Id = new Guid("7a2fbc72-bb33-49de-bd23-c78fceb367fc"),
                            Name = "Mandrake Root"
                        },
                        new
                        {
                            Id = new Guid("b5f336e2-c226-4389-aac3-2499325a3de9"),
                            Name = "Spiders Silk"
                        },
                        new
                        {
                            Id = new Guid("c22bec27-a880-4f2a-b380-12dcd99c61fe"),
                            Name = "Sulfurous Ash"
                        });
                });

            modelBuilder.Entity("SpellBookApi.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spells");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eacc5169-b2a7-41ad-92c3-dbb1a5e7af06"),
                            Name = "Flamestrike"
                        },
                        new
                        {
                            Id = new Guid("fe462ec7-b30c-4987-8a8e-5f7dbd8e0cfa"),
                            Name = "Teleport"
                        },
                        new
                        {
                            Id = new Guid("b512d7cf-b331-4b54-8dae-d1228d128e8d"),
                            Name = "Greater Heal"
                        },
                        new
                        {
                            Id = new Guid("fd630a57-2352-4731-b25c-db9cc7601b16"),
                            Name = "Portal"
                        },
                        new
                        {
                            Id = new Guid("98929bd4-f099-41eb-a994-f1918b724b5a"),
                            Name = "Summon"
                        });
                });

            modelBuilder.Entity("ReagentSpell", b =>
                {
                    b.HasOne("SpellBookApi.Entities.Reagent", null)
                        .WithMany()
                        .HasForeignKey("ReagentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellBookApi.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
